# Generated by Django 4.1.7 on 2023-03-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('gid', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, max_length=20, null=True)),
                ('posicion', models.CharField(blank=True, max_length=50, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=50, null=True)),
                ('detalles', models.CharField(blank=True, max_length=50, null=True)),
                ('signature', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'resguardos',
            },
        ),
    ]
