# Generated by Django 4.1.7 on 2023-03-05 04:26

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='signature',
        ),
        migrations.AddField(
            model_name='signature',
            name='firma',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
    ]
